### ISSUE TITLE
openNLP error

### ISSUE THREAD

**Issue by keighrim** [brandeis-nlp/Galaxy#4]
The OpenNLP parser gives a Java error

``` bash
java.lang.NullPointerException","stacktrace":"java.lang.NullPointerException
    at org.lappsgrid.serialization.json.LIFJsonSerialization.getText(LIFJsonSerialization.java:36)
    at edu.brandeis.cs.lappsgrid.opennlp.Parser.execute(Parser.java:57)
    at edu.brandeis.cs.lappsgrid.opennlp.OpenNLPAbstractWebService.execute(OpenNLPAbstractWebService.java:336)
    at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at jp.go.nict.langrid.servicecontainer.decorator.ServiceDecorator.doDecorate(ServiceDecorator.java:50)
    at jp.go.nict.langrid.servicecontainer.decorator.DecoratorChain.doDecorate(DecoratorChain.java:82)
    at jp.go.nict.langrid.servicecontainer.handler.ServiceInvocationHandler.invoke(ServiceInvocationHandler.java:28)
    at com.sun.proxy.$Proxy72.execute(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor246.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.axis.providers.java.RPCProvider.invokeMethod(RPCProvider.java:397)
    at org.apache.axis.providers.java.RPCProvider.processMessage(RPCProvider.java:186)
    at jp.go.nict.langrid.servicecontainer.handler.axis.SGJavaProvider.processMessage(SGJavaProvider.java:158)
    at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:323)
    at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
    at 
...
```

Probably because it is an old version.
Or probably because of input format.

**Comment by keighrim** [comment]
Could not reproduce locally using 2.0.0, nor 2.0.1. Input was 

``` json
{"discriminator":"http://vocab.lappsgrid.org/ns/media/jsonld#lif","payload":{"@context":"http://vocab.lappsgrid.org/context-1.0.0.jsonld","metadata":{},"text":{"@value":"\n\n\nMessage-ID: <4232569.1075852475436.JavaMail.evans@thyme>\nDate: Sat, 25 Aug 2001 16:35:13 -0700 (PDT)\nFrom: donk@prestongates.com\nSubject: PRIVILEGED AND CONFIDENTIAL - Scott Jones Draft\nMime-Version: 1.0\nContent-Type: text/plain; charset=us-ascii\nContent-Transfer-Encoding: 7bit\n\n\nAttached is the draft testimony of Scott Jones.\n\nComments should be received no later than 3:00 PM EST on Sunday, August 26.\nAll comments and suggestions need to be in writing and can be faxed (not\nE-mailed) to Dan Watkiss at 202-857-2131.  Also, if your suggestion is a\nproposed addition, please write out the exact language you would propose we\nincorporate into the testimony and where you would place the addition.\n\nDonald A. Kaplan, Esq.\nPreston Gates Ellis &\n  Rouvelas Meeds LLP\nSuite 500\n1735 New York Avenue, N.W.\nWashington, D.C.  20006\nPh: (202) 662-8466\nFax: (202) 331-1024\ndonk@prestongates.com\n\n(See attached file: TFG SJones Draft 8-25-01.doc)(See attached file:\nExhibit STJ-6.xls)(See attached file: Exhibit STJ-3.xls)(See attached file:\nExhibit STJ-4.xls)(See attached file: Exhibit STJ-5.xls)(See attached file:\nExhibit STJ-2.doc)\n\nCONFIDENTIALITY NOTE:\nThis email message is intended solely for the individual or individuals\nnamed above.  It may contain confidential attorney-client privileged\ninformation and/or attorney work product.  If the reader of this message is\nnot the intended recipient, you are requested not to read, copy or\ndistribute it or any of the information it contains.  Please delete it\nimmediately and notify the sender by return email or by telephone.  Thank\nyou.\n\n  <<TFG SJones Draft 8-25-01.doc>>  <<Exhibit STJ-6.xls>>  <<Exhibit\n  STJ-3.xls>>  <<Exhibit STJ-4.xls>>  <<Exhibit STJ-5.xls>>  <<Exhibit\n  STJ-2.doc>>\n\n - TFG SJones Draft 8-25-01.doc \n - Exhibit STJ-6.xls \n - Exhibit STJ-3.xls \n - Exhibit STJ-4.xls \n - Exhibit STJ-5.xls \n - Exhibit STJ-2.doc \n\n\n"},"views":[{"metadata":{"contains":{"http://vocab.lappsgrid.org/Sentence":{"producer":"org.anc.lapps.stanford.SentenceSplitter:2.0.0","type":"sentence:stanford"}}},"annotations":[{"id":"s0","start":3,"end":331,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s1","start":333,"end":408,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s2","start":409,"end":523,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s3","start":525,"end":701,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s4","start":703,"end":725,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s5","start":726,"end":937,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s6","start":937,"end":975,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s7","start":975,"end":1013,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s8","start":1013,"end":1051,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s9","start":1051,"end":1089,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s10","start":1089,"end":1127,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s11","start":1127,"end":1239,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s12","start":1241,"end":1337,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s13","start":1339,"end":1491,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s14","start":1493,"end":1576,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s15","start":1578,"end":1588,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s16","start":1592,"end":1619,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s17","start":1619,"end":1642,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s18","start":1642,"end":1667,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s19","start":1667,"end":1690,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s20","start":1690,"end":1713,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s21","start":1713,"end":1738,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s22","start":1738,"end":1773,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s23","start":1773,"end":1795,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s24","start":1795,"end":1817,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s25","start":1817,"end":1839,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s26","start":1839,"end":1861,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s27","start":1861,"end":1883,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"},{"id":"s28","start":1883,"end":1886,"@type":"http://vocab.lappsgrid.org/Sentence","label":"Sentence"}]}]}}
```

**Comment by keighrim** [comment]
Closing issue as this fork is archived.
